language: node_js
node_js:
  - "node"

cache: npm

jobs:
  include:
    - stage: Tests
      name: Lint
      script: npm run lint
    - script: npm run test:unit
      name: Unit tests
    - stage: Deploy
      name: Deploy to Github Pages
      script: npm run build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: dist
        on:
          branch: master
